#!/bin/sh
cd "${0%/*}" || exit 1

#------------------------------------------------------------------------------
# Allclean - channelHartmannSpanwise
#
# Removes the generated mesh, the written times, postProcessing and the logs.
#------------------------------------------------------------------------------

echo "Allclean: removendo malha, tempos, postProcessing e log.*"

rm -rf constant/polyMesh
rm -rf postProcessing
rm -rf processor*
rm -f  log.* time.txt
rm -rf [1-9]* [0-9]*.[0-9]*

ls
