#!/bin/bash
# -----------------------------------------------------------------------------
# Run every verification case and report the metrics used in docs/verification.md
#
# Usage:  ./verify.sh            # runs and prints a report
#         ./verify.sh --report   # also rewrites docs/verification.md
#
# Requires an OpenFOAM 6 environment (source .../OpenFOAM-6/etc/bashrc) with
# the mhdturbFoam-hardened binary on PATH.
# -----------------------------------------------------------------------------
set -u

cd "$(dirname "$0")" || exit 1

WRITE_REPORT=no
[ "${1:-}" = "--report" ] && WRITE_REPORT=yes

if ! command -v mhdturbFoam >/dev/null 2>&1; then
    echo "ERROR: mhdturbFoam not found on PATH. Build src/ and source the" >&2
    echo "       OpenFOAM 6 environment first." >&2
    exit 1
fi

CASES="channelHartmann channelHartmannSpanwise channelHartmannPeriodic"

# run_one <case> -> prints one whitespace-separated row
run_one() {
    local c=$1
    local d="cases/$c"

    (
        cd "$d" || exit 1
        rm -rf [1-9]* [0-9]*.[0-9]* postProcessing polyMesh log.* time.txt
        blockMesh > log.blockMesh 2>&1 || { echo "$c blockMesh FAILED"; exit 1; }

        local t0 t1 rc steps end cont mag pfin
        t0=$(date +%s)
        mhdturbFoam > log.mhdturbFoam 2>&1
        rc=$?
        t1=$(date +%s)

        steps=$(grep -c "Time = " log.mhdturbFoam)
        end=$(grep -c "^End" log.mhdturbFoam)
        cont=$(grep "sum local" log.mhdturbFoam \
               | grep -oE "sum local = [0-9.e+-]+" | awk '{print $4}' \
               | sort -g | tail -1)
        mag=$(grep "magnetic flux" log.mhdturbFoam \
              | grep -oE "= [0-9.e+-]+$" | awk '{print $2}' \
              | sort -g | tail -1)
        pfin=$(grep "Solving for p," log.mhdturbFoam \
               | grep -oE "Final residual = [0-9.e+-]+" | awk '{print $4}' \
               | sort -g | tail -1)

        echo "$c $rc $steps $end ${cont:-n/a} ${mag:-n/a} ${pfin:-n/a} $((t1-t0))"
    )
}

echo "mhdturbFoam-hardened verification"
echo "binary: $(command -v mhdturbFoam)"
echo

ROWS=""
for c in $CASES; do
    row=$(run_one "$c")
    ROWS="$ROWS$row"$'\n'
    echo "$row"
done

if [ "$WRITE_REPORT" = yes ]; then
    {
        echo "# Verification report"
        echo
        echo "Generated by \`./verify.sh --report\` on $(date -u '+%Y-%m-%d %H:%M UTC')."
        echo
        echo "| case | exit | steps | reached \`End\` | max continuity error | max magnetic flux divergence error | max final p residual | s |"
        echo "|---|---|---|---|---|---|---|---|"
        printf '%s' "$ROWS" | while read -r c rc steps end cont mag pfin secs; do
            [ -z "${c:-}" ] && continue
            echo "| $c | $rc | $steps | $end | $cont | $mag | $pfin | $secs |"
        done
    } > docs/verification.md
    echo
    echo "written: docs/verification.md"
fi
